window.DW_QUOTES = [
  {
    "id": "HP-001",
    "world": "Harry Potter",
    "character": "Albus Dumbledore",
    "source": "Harry Potter and the Philosopher's Stone",
    "quote": "It does not do to dwell on dreams and forget to live.",
    "highlight": "LIVE IN THE PRESENT",
    "theme": "Presence; action; perspective",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "HP-002",
    "world": "Harry Potter",
    "character": "Albus Dumbledore",
    "source": "Harry Potter and the Chamber of Secrets",
    "quote": "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    "highlight": "OUR CHOICES",
    "theme": "Character; agency; self-belief",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "HP-003",
    "world": "Harry Potter",
    "character": "Hagrid",
    "source": "Harry Potter and the Goblet of Fire",
    "quote": "What's comin' will come, an' we'll meet it when it does.",
    "highlight": "WE'LL MEET IT",
    "theme": "Courage; anxiety; resilience",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "HP-004",
    "world": "Harry Potter",
    "character": "Sirius Black",
    "source": "Harry Potter and the Order of the Phoenix",
    "quote": "The world isn't split into good people and Death Eaters.",
    "highlight": "NOT BLACK AND WHITE",
    "theme": "Perspective; judgment; maturity",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "HP-005",
    "world": "Harry Potter",
    "character": "Albus Dumbledore",
    "source": "Harry Potter and the Goblet of Fire",
    "quote": "It matters not what someone is born, but what they grow to be!",
    "highlight": "WHAT THEY GROW TO BE",
    "theme": "Growth; identity; self-belief",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "HP-006",
    "world": "Harry Potter",
    "character": "Albus Dumbledore",
    "source": "Harry Potter and the Deathly Hallows",
    "quote": "Do not pity the dead, Harry. Pity the living.",
    "highlight": "PITY THE LIVING",
    "theme": "Life; love; perspective",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "HP-007",
    "world": "Harry Potter",
    "character": "Albus Dumbledore",
    "source": "Harry Potter and the Deathly Hallows",
    "quote": "Why on earth should that mean that it is not real?",
    "highlight": "IT IS NOT REAL?",
    "theme": "Meaning; inner life; perspective",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DBZ-001",
    "world": "Dragon Ball / DBZ",
    "character": "Vegeta",
    "source": "Dragon Ball Z — Majin Vegeta arc",
    "quote": "There is one thing a Saiyan always keeps: his pride!",
    "highlight": "HIS PRIDE",
    "theme": "Identity; resolve; pride",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DBZ-002",
    "world": "Dragon Ball / DBZ",
    "character": "Vegeta",
    "source": "Dragon Ball Z — Buu Saga",
    "quote": "You're better than me, Kakarot. You are the best.",
    "highlight": "YOU ARE THE BEST",
    "theme": "Humility; growth; respect",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-001",
    "world": "Marvel",
    "character": "Uncle Ben",
    "source": "Spider-Man (2002)",
    "quote": "With great power comes great responsibility.",
    "highlight": "GREAT RESPONSIBILITY",
    "theme": "Responsibility; character",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-002",
    "world": "Marvel",
    "character": "Aunt May",
    "source": "Spider-Man 2 (2004)",
    "quote": "Sometimes, to do what's right, we have to be steady.",
    "highlight": "DO WHAT'S RIGHT",
    "theme": "Sacrifice; courage; duty",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-003",
    "world": "Marvel",
    "character": "Otto Octavius",
    "source": "Spider-Man 2 (2004)",
    "quote": "Intelligence is not a privilege. It's a gift.",
    "highlight": "IT'S A GIFT",
    "theme": "Purpose; service; responsibility",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-004",
    "world": "Marvel",
    "character": "Tony Stark",
    "source": "Spider-Man: Homecoming (2017)",
    "quote": "If you're nothing without this suit, then you shouldn't have it.",
    "highlight": "NOTHING WITHOUT THIS SUIT",
    "theme": "Self-worth; competence; growth",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-005",
    "world": "Marvel",
    "character": "Steve Rogers",
    "source": "Captain America: The First Avenger (2011)",
    "quote": "I can do this all day.",
    "highlight": "ALL DAY",
    "theme": "Perseverance; courage",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-006",
    "world": "Marvel",
    "character": "Thor",
    "source": "Thor: The Dark World (2013)",
    "quote": "I'd rather be a good man than a great king.",
    "highlight": "A GOOD MAN",
    "theme": "Character; humility; values",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-007",
    "world": "Marvel",
    "character": "Ancient One",
    "source": "Doctor Strange (2016)",
    "quote": "Death is what gives life meaning.",
    "highlight": "GIVES LIFE MEANING",
    "theme": "Mortality; purpose; urgency",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-008",
    "world": "Marvel",
    "character": "Frigga",
    "source": "Avengers: Endgame (2019)",
    "quote": "Thor: I'm completely destroyed. My mom died. And my brother— and my planet. It's just all gone.\nFrigga: Everyone fails at who they're supposed to be, Thor. The measure of a person, of a hero... is how well they succeed at being who they are.",
    "highlight": "HOW WELL THEY SUCCEED AT BEING WHO THEY ARE",
    "theme": "Self-acceptance; identity; failure; expectations; authenticity; rebuilding",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-009",
    "world": "Marvel",
    "character": "Ancient One",
    "source": "Doctor Strange (2016)",
    "quote": "We never lose our demons, Mordo. We only learn to live above them.",
    "highlight": "WE ONLY LEARN TO LIVE ABOVE THEM",
    "theme": "Self-mastery; acceptance; resilience; inner struggle",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-010",
    "world": "Marvel",
    "character": "Natasha Romanoff / Black Widow",
    "source": "Avengers: Endgame (2019)",
    "quote": "I don't judge people on their worst mistakes.",
    "highlight": "WORST MISTAKES",
    "theme": "Forgiveness; compassion; perspective; redemption",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-011",
    "world": "Marvel",
    "character": "Thor Odinson",
    "source": "Thor: Ragnarok (2017)",
    "quote": "I choose to run towards my problems, and not away from them. Because that's what heroes do.",
    "highlight": "RUN TOWARDS MY PROBLEMS",
    "theme": "Courage; confronting problems; action; responsibility",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-012",
    "world": "Marvel",
    "character": "Tony Stark / Iron Man",
    "source": "Avengers: Endgame (2019)",
    "quote": "It's not about how much we lost. It's about how much we have left.",
    "highlight": "HOW MUCH WE HAVE LEFT",
    "theme": "Gratitude; resilience; perspective; moving forward",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-013",
    "world": "Marvel",
    "character": "Natasha Romanoff / Black Widow",
    "source": "Black Widow (2021)",
    "quote": "At some point, we all have to choose between what the world wants you to be and who you are.",
    "highlight": "WHO YOU ARE",
    "theme": "Identity; authenticity; courage; independence",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-014",
    "world": "Marvel",
    "character": "Shuri",
    "source": "Black Panther (2018)",
    "quote": "Just because something works doesn't mean it can't be improved.",
    "highlight": "IT CAN'T BE IMPROVED",
    "theme": "Continuous improvement; curiosity; growth; innovation",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-015",
    "world": "Marvel",
    "character": "Dr. Abraham Erskine",
    "source": "Captain America: The First Avenger (2011)",
    "quote": "Whatever happens tomorrow, you must promise me one thing. That you will stay who you are, not a perfect soldier, but a good man.",
    "highlight": "NOT A PERFECT SOLDIER, BUT A GOOD MAN",
    "theme": "Character; integrity; humility; staying true to yourself; goodness",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-016",
    "world": "Marvel",
    "character": "Peggy Carter",
    "source": "Captain America: The First Avenger (2011)",
    "quote": "The world has changed and none of us can go back. All we can do is our best, and sometimes the best that we can do is to start over.",
    "highlight": "SOMETIMES THE BEST THAT WE CAN DO IS TO START OVER",
    "theme": "Starting over; acceptance; change; resilience; moving forward",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-017",
    "world": "Marvel",
    "character": "Loki",
    "source": "Avengers: Infinity War (2018)",
    "quote": "I assure you, brother, the sun will shine on us again.",
    "highlight": "THE SUN WILL SHINE ON US AGAIN",
    "theme": "Hope; optimism; difficult times; perseverance",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-018",
    "world": "Marvel",
    "character": "Steve Rogers / Captain America",
    "source": "Captain America: The Winter Soldier (2014)",
    "quote": "I'm with you 'til the end of the line.",
    "highlight": "'TIL THE END OF THE LINE",
    "theme": "Loyalty; friendship; commitment; standing by others",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "MAR-019",
    "world": "Marvel",
    "character": "Namor",
    "source": "Black Panther: Wakanda Forever (2022)",
    "quote": "How is never as important as why.",
    "highlight": "HOW IS NEVER AS IMPORTANT AS WHY",
    "theme": "Purpose; priorities; intention; decision-making",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-001",
    "world": "DC",
    "character": "Alfred Pennyworth",
    "source": "Batman Begins (2005)",
    "quote": "Why do we fall, sir? So that we can learn to pick ourselves up.",
    "highlight": "PICK OURSELVES UP",
    "theme": "Resilience; recovery",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-002",
    "world": "DC",
    "character": "Ra's al Ghul / Ducard",
    "source": "Batman Begins (2005)",
    "quote": "Training is nothing! Will is everything!",
    "highlight": "WILL IS EVERYTHING",
    "theme": "Willpower; discipline",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-003",
    "world": "DC",
    "character": "Ra's al Ghul / Ducard",
    "source": "Batman Begins (2005)",
    "quote": "Always mind your surroundings.",
    "highlight": "MIND YOUR SURROUNDINGS",
    "theme": "Awareness; discipline",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-004",
    "world": "DC",
    "character": "Bruce Wayne / Batman",
    "source": "Batman Begins (2005)",
    "quote": "It's not who I am underneath, but what I do that defines me.",
    "highlight": "WHAT I DO",
    "theme": "Action; character",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-005",
    "world": "DC",
    "character": "Bane",
    "source": "The Dark Knight Rises (2012)",
    "quote": "Peace has cost you your strength. Victory has defeated you.",
    "highlight": "VICTORY HAS DEFEATED YOU",
    "theme": "Complacency; discipline; vigilance",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-006",
    "world": "DC",
    "character": "Batman",
    "source": "The Dark Knight Rises (2012)",
    "quote": "A hero can be anyone.",
    "highlight": "A HERO CAN BE ANYONE",
    "theme": "Kindness; service; courage",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-007",
    "world": "DC",
    "character": "Superman",
    "source": "Justice League Unlimited — Destroyer",
    "quote": "Batman won't quit so long as he can draw breath.",
    "highlight": "WON'T QUIT",
    "theme": "Perseverance; faith in others",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DC-008",
    "world": "DC",
    "character": "Superman",
    "source": "Justice League Unlimited — Destroyer",
    "quote": "I feel like I live in a world made of cardboard.",
    "highlight": "WORLD MADE OF CARDBOARD",
    "theme": "Restraint; responsibility; power",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-001",
    "world": "Rocky",
    "character": "Rocky Balboa",
    "source": "Rocky (1976)",
    "quote": "'Cause all I wanna do is go the distance. Nobody's ever gone the distance with Creed, and if I can go that distance, you see, and that bell rings and I'm still standin', I'm gonna know for the first time in my life, see, that I weren't just another bum from the neighborhood.",
    "highlight": "GO THE DISTANCE",
    "theme": "Endurance; self-worth; redefining success",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-002",
    "world": "Rocky",
    "character": "Apollo Creed",
    "source": "Rocky III (1982)",
    "quote": "Apollo: He's hooking. He's hooking. He's hooking! Damn, Rock, come on! What's the matter with you?\nRocky: Tomorrow. Let's do it tomorrow.\nApollo: There is no tomorrow! THERE IS NO TOMORROW! THERE IS NO TOMORROW!",
    "highlight": "THERE IS NO TOMORROW!",
    "theme": "Action now; discipline; urgency; commitment",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-003",
    "world": "Rocky",
    "character": "Rocky Balboa",
    "source": "Rocky III (1982)",
    "quote": "Nothing is real if you don't believe in who you are!",
    "highlight": "BELIEVE IN WHO YOU ARE",
    "theme": "Self-belief; fear; identity",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-004",
    "world": "Rocky",
    "character": "Adrian Balboa",
    "source": "Rocky III (1982)",
    "quote": "There's nothing wrong with being afraid!",
    "highlight": "NOTHING WRONG WITH BEING AFRAID",
    "theme": "Fear; courage; intrinsic motivation",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-005",
    "world": "Rocky",
    "character": "Apollo Creed",
    "source": "Rocky III (1982)",
    "quote": "You lost your edge.",
    "highlight": "GET YOUR EDGE BACK",
    "theme": "Recovery; hunger; training",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-006",
    "world": "Rocky",
    "character": "Rocky Balboa",
    "source": "Rocky Balboa (2006)",
    "quote": "It ain’t about how hard you hit. It’s about how hard you can get hit and keep moving forward. It's about how much you can take and keep moving forward!",
    "highlight": "KEEP MOVING FORWARD",
    "theme": "Resilience; perseverance; adversity; forward momentum",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NBD-001",
    "world": "Never Back Down",
    "character": "Jean Roqua",
    "source": "Never Back Down (2008)",
    "quote": "Never give up. Never back down.",
    "highlight": "NEVER GIVE UP",
    "theme": "Perseverance; resolve",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-001",
    "world": "Disney & Animation",
    "character": "Rafiki",
    "source": "The Lion King (1994)",
    "quote": "The past can hurt.",
    "highlight": "RUN FROM IT OR LEARN FROM IT",
    "theme": "Past; learning; courage",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-002",
    "world": "Disney & Animation",
    "character": "Mufasa",
    "source": "The Lion King (1994)",
    "quote": "You’ve forgotten who you are, and so forgotten me. Look inside yourself, Simba. You are more than what you have become. You must take your place in the Circle of Life.",
    "highlight": "YOU ARE MORE THAN WHAT YOU HAVE BECOME",
    "theme": "Identity; self-belief; potential; responsibility; purpose",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-004",
    "world": "Disney & Animation",
    "character": "Master Oogway",
    "source": "Kung Fu Panda (2008)",
    "quote": "Yesterday is history, tomorrow is a mystery.",
    "highlight": "TODAY IS A GIFT",
    "theme": "Presence; anxiety; perspective",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-005",
    "world": "Disney & Animation",
    "character": "Master Oogway",
    "source": "Kung Fu Panda (2008)",
    "quote": "Let go of the illusion of control.",
    "highlight": "ILLUSION OF CONTROL",
    "theme": "Control; patience; mentorship",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-006",
    "world": "Disney & Animation",
    "character": "Mr. Ping",
    "source": "Kung Fu Panda (2008)",
    "quote": "There is no secret ingredient.",
    "highlight": "NO SECRET INGREDIENT",
    "theme": "Self-belief; simplicity",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-007",
    "world": "Disney & Animation",
    "character": "Olaf",
    "source": "Frozen (2013)",
    "quote": "Love is putting someone else's needs before yours.",
    "highlight": "LOVE IS...",
    "theme": "Love; selflessness",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-008",
    "world": "Disney & Animation",
    "character": "Shrek",
    "source": "Shrek (2001)",
    "quote": "Ogres have layers.",
    "highlight": "WE BOTH HAVE LAYERS",
    "theme": "Complexity; empathy; identity",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "SH-001",
    "world": "Sherlock Holmes",
    "character": "Sherlock Holmes",
    "source": "A Scandal in Bohemia",
    "quote": "It is a capital mistake to theorise before one has data. Insensibly one begins to twist facts to suit theories, instead of theories to suit facts.",
    "highlight": "THEORIES TO SUIT FACTS",
    "theme": "Evidence; judgment; thinking",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "SH-002",
    "world": "Sherlock Holmes",
    "character": "Sherlock Holmes",
    "source": "The Sign of the Four",
    "quote": "I never guess. It is a shocking habit,—destructive to the logical faculty.",
    "highlight": "I NEVER GUESS",
    "theme": "Reasoning; discipline",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "SH-003",
    "world": "Sherlock Holmes",
    "character": "Sherlock Holmes",
    "source": "The Hound of the Baskervilles",
    "quote": "There is nothing more stimulating than a case where everything goes against you. We must cast round for another scent.",
    "highlight": "EVERYTHING GOES AGAINST YOU",
    "theme": "Resilience; problem-solving",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "SH-004",
    "world": "Sherlock Holmes",
    "character": "Sherlock Holmes",
    "source": "The Red Circle",
    "quote": "Education never ends, Watson. It is a series of lessons with the greatest for the last.",
    "highlight": "EDUCATION NEVER ENDS",
    "theme": "Learning; growth; curiosity",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "SH-005",
    "world": "Sherlock Holmes",
    "character": "Sherlock Holmes",
    "source": "The Sign of the Four",
    "quote": "When you have eliminated the impossible, whatever remains, however improbable, must be the truth.",
    "highlight": "ELIMINATED THE IMPOSSIBLE",
    "theme": "Problem-solving; logic",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "SH-006",
    "world": "Sherlock Holmes",
    "character": "Sherlock Holmes",
    "source": "A Scandal in Bohemia",
    "quote": "You see, but you do not observe. The distinction is clear.",
    "highlight": "YOU DO NOT OBSERVE",
    "theme": "Attention; presence",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "SH-007",
    "world": "Sherlock Holmes",
    "character": "Sherlock Holmes",
    "source": "The Boscombe Valley Mystery",
    "quote": "There is nothing more deceptive than an obvious fact.",
    "highlight": "AN OBVIOUS FACT",
    "theme": "Critical thinking",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-007",
    "world": "Rocky",
    "character": "Apollo Creed & Tony “Duke” Evers",
    "source": "Rocky II (1979)",
    "quote": "Apollo: Do you think I beat him the last time? Do you?\nDuke: You got the decision.\nApollo: Man, I won, but I didn't beat him!\nDuke: What are you afraid of?\nApollo: Tony.\nDuke: Honest?\nApollo: Yeah, honest.\nDuke: He's all wrong for us, baby. I saw you beat that man like I never saw no man get beat before, and the man kept coming after you. We don't need that kind of man in our life.",
    "highlight": "I WON, BUT I DIDN'T BEAT HIM",
    "theme": "Relentlessness; resilience; refusing to stay down",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ROC-008",
    "world": "Rocky",
    "character": "Rocky Balboa",
    "source": "Rocky IV (1985)",
    "quote": "DRAGOOOOOOOO!",
    "highlight": "DRAGOOOOOOOO!",
    "theme": "Training; discipline; perseverance; motivational trigger",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NBD-002",
    "world": "Never Back Down",
    "character": "Jake Tyler",
    "source": "Never Back Down (2008)",
    "quote": "Well if that's what you believe, then he was right. You gave up. Sometimes fighting the fight means that you have to do the one thing you don't want to do. You have to fight for his forgiveness. You can't just hide here forever. At least I can't. I'm gonna stop this guy. Win, lose, it makes no difference. It ends tonight. This is my fight. Everyone's got one.",
    "highlight": "THIS IS MY FIGHT. EVERYONE'S GOT ONE.",
    "theme": "Facing what you avoid; courage; accountability; difficult choices",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NBD-003",
    "world": "Never Back Down",
    "character": "Jean Roqua & Jake Tyler",
    "source": "Never Back Down (2008)",
    "quote": "Jean: Jake, no matter what happens, control the outcome. It's on you.\nJake: Always has been.\nJean: It's on you, always has been, always will be.",
    "highlight": "IT'S ON YOU. ALWAYS HAS BEEN, ALWAYS WILL BE.",
    "theme": "Personal responsibility; agency; accountability",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NBD-004",
    "world": "Never Back Down",
    "character": "Ryan McCarthy",
    "source": "Never Back Down (2008)",
    "quote": "If you gonna be the best, you have to take out the best.",
    "highlight": "TAKE OUT THE BEST",
    "theme": "Face the biggest challenge; growth through challenge",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NBD-005",
    "world": "Never Back Down",
    "character": "Jake Tyler",
    "source": "Never Back Down (2008)",
    "quote": "I don't want to be angry anymore. The only time I'm not is when I'm in the gym, and I'm training with you.",
    "highlight": "I DON'T WANT TO BE ANGRY ANYMORE",
    "theme": "Self-improvement; emotional control; training; change",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "AC-001",
    "world": "Alex Cross",
    "character": "Narrator (about Cruz)",
    "source": "Target: Alex Cross",
    "quote": "A weaker man might be focused on finding drugs to kill the pain. But Cruz was neither ordinary nor weak. He'd long ago trained himself to be a superior man, one who could control his emotions, mind, and pain.",
    "highlight": "CONTROL HIS EMOTIONS, MIND, AND PAIN",
    "theme": "Mental toughness; emotional control; discipline; self-mastery",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "AC-002",
    "world": "Alex Cross",
    "character": "Alex Cross",
    "source": "Cross",
    "quote": "The most striking thing about beautiful churches, to me, is that they were mostly designed by people who were inspired by a belief in something larger and more important than themselves, and this is how I try to lead my own life.",
    "highlight": "SOMETHING LARGER AND MORE IMPORTANT THAN THEMSELVES",
    "theme": "Purpose; meaning; service; humility; values",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "ANI-010",
    "world": "Disney & Animation",
    "character": "Po & Lord Shen",
    "source": "Kung Fu Panda 2 (2011)",
    "quote": "Shen: How did you? How did you do it?\nPo: You know? You just keep your elbows up, keep the shoulders loose?\nShen: Not that, how did you find peace? I took away your parents, everything, I scarred you for life.\nPo: See, that’s the thing Shen, scars heal.\nShen: No they don’t, wounds heal.\nPo: Oh yeah? Well, what do scars do, they fade I guess?\nShen: I don’t care what scars do.\nPo: You should Shen, you gotta let go of that stuff from the past, cause it just doesn’t matter, the only thing that matters is what you choose to be now.",
    "highlight": "THE ONLY THING THAT MATTERS IS WHAT YOU CHOOSE TO BE NOW",
    "theme": "Letting go of the past; identity; healing; choice; inner peace",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "DW-716",
    "world": "Disney & Animation",
    "character": "Mufasa",
    "source": "The Lion King (1994)",
    "quote": "Everything you see exists together in a delicate balance.",
    "highlight": "DELICATE BALANCE",
    "theme": "Perspective; balance; interconnectedness",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-001",
    "world": "General Wisdom",
    "character": "Sir Edmund Hillary / evolved saying",
    "source": "Interview tradition / attribution nuanced",
    "quote": "It is not the mountain we conquer, but ourselves.",
    "highlight": "SELF-MASTERY",
    "theme": "Self-mastery; challenge; discipline",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP — attribution nuanced"
  },
  {
    "id": "NF-002",
    "world": "General Wisdom",
    "character": "Squire Bill Widener (quoted by Theodore Roosevelt)",
    "source": "Theodore Roosevelt, Autobiography (1913)",
    "quote": "Do what you can, with what you've got, where you are.",
    "highlight": "DO WHAT YOU CAN",
    "theme": "Action; resourcefulness; starting",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-003",
    "world": "General Wisdom",
    "character": "Les Brown",
    "source": "Live Your Dreams (1992)",
    "quote": "You are never too old to set another goal or to dream a new dream.",
    "highlight": "ANOTHER GOAL",
    "theme": "Reinvention; hope; goals",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-004",
    "world": "General Wisdom",
    "character": "Proverb / uncertain origin",
    "source": "Modern proverb",
    "quote": "It always seems impossible until it's done.",
    "highlight": "UNTIL IT'S DONE",
    "theme": "Perseverance; possibility",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP — attribution uncertain"
  },
  {
    "id": "NF-005",
    "world": "General Wisdom",
    "character": "J. K. Rowling",
    "source": "Harvard commencement address (2008)",
    "quote": "And so rock bottom became the solid foundation on which I rebuilt my life.",
    "highlight": "SOLID FOUNDATION",
    "theme": "Failure; rebuilding; resilience",
    "fullTextStatus": "SCENE/PASSAGE — FULL TEXT MAY BE NEEDED",
    "status": "KEEP"
  },
  {
    "id": "NF-006",
    "world": "General Wisdom",
    "character": "Mary Anne Radmacher",
    "source": "Author's poem/artwork; later book",
    "quote": "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'",
    "highlight": "I WILL TRY AGAIN TOMORROW",
    "theme": "Courage; perseverance; resilience",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-009",
    "world": "General Wisdom",
    "character": "Sarah Williams",
    "source": "The Old Astronomer to His Pupil",
    "quote": "I have loved the stars too fondly to be fearful of the night.",
    "highlight": "NOT FEARFUL OF THE NIGHT",
    "theme": "Hope; adversity; courage",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-011",
    "world": "General Wisdom",
    "character": "Jim Henson",
    "source": "Recalled by Brian Henson",
    "quote": "If you want to be fascinating, be fascinated.",
    "highlight": "BE FASCINATED",
    "theme": "Curiosity; creativity; presence",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-012",
    "world": "General Wisdom",
    "character": "Dale Carnegie",
    "source": "How to Win Friends and Influence People",
    "quote": "To be interesting, be interested.",
    "highlight": "BE INTERESTED",
    "theme": "Listening; connection; curiosity",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-015",
    "world": "General Wisdom",
    "character": "Attribution uncertain",
    "source": "Common modern quotation",
    "quote": "It is never too late to be what you might have been.",
    "highlight": "IT IS NEVER TOO LATE",
    "theme": "Reinvention; possibility; hope",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP — attribution uncertain"
  },
  {
    "id": "NF-016",
    "world": "General Wisdom",
    "character": "Henry Ford",
    "source": "My Life and Work",
    "quote": "Failure is only the opportunity more intelligently to begin again.",
    "highlight": "BEGIN AGAIN",
    "theme": "Failure; learning; resilience",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-018",
    "world": "General Wisdom",
    "character": "Richie Norton",
    "source": "Author-attributed",
    "quote": "Every sunset is an opportunity to reset.",
    "highlight": "OPPORTUNITY TO RESET",
    "theme": "Reset; reflection; second chances",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-020",
    "world": "General Wisdom",
    "character": "Modern paraphrase of Buddhist teaching",
    "source": "Modern wording",
    "quote": "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
    "highlight": "DESERVE YOUR LOVE AND AFFECTION",
    "theme": "Self-compassion; kindness; self-respect",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP — attribution corrected"
  },
  {
    "id": "NF-021",
    "world": "General Wisdom",
    "character": "Steve Jobs",
    "source": "Stanford commencement address (2005)",
    "quote": "Your time is limited, so don't waste it living someone else's life.",
    "highlight": "YOUR TIME IS LIMITED",
    "theme": "Authenticity; courage; purpose",
    "fullTextStatus": "FULL TEXT RECEIVED",
    "status": "KEEP"
  },
  {
    "id": "NF-022",
    "world": "General Wisdom",
    "character": "Steve Jobs",
    "source": "Stanford commencement address (2005)",
    "quote": "You can't connect the dots looking forward; you can only connect them looking backwards.",
    "highlight": "CONNECT THE DOTS",
    "theme": "Trust; uncertainty; perspective",
    "fullTextStatus": "SCENE/PASSAGE — FULL TEXT MAY BE NEEDED",
    "status": "KEEP"
  },
  {
    "id": "NF-023",
    "world": "General Wisdom",
    "character": "Aesop tradition",
    "source": "The Lion and the Mouse — traditional moral",
    "quote": "No act of kindness, no matter how small, is ever wasted.",
    "highlight": "NO ACT OF KINDNESS",
    "theme": "Kindness; generosity; humanity",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-024",
    "world": "General Wisdom",
    "character": "Apple / Think Different campaign",
    "source": "Think Different (1997); Steve Jobs narration",
    "quote": "Here's to the crazy ones… the people who are crazy enough to think that they can change the world are the ones who do.",
    "highlight": "CRAZY ENOUGH TO CHANGE THE WORLD",
    "theme": "Individuality; ambition; creativity",
    "fullTextStatus": "FULL TEXT RECEIVED",
    "status": "KEEP"
  },
  {
    "id": "NF-027",
    "world": "General Wisdom",
    "character": "Arnold Schwarzenegger",
    "source": "1982 Boston Globe interview",
    "quote": "When you go through hardships and decide not to surrender, that is strength.",
    "highlight": "DECIDE NOT TO SURRENDER",
    "theme": "Adversity; resilience; strength",
    "fullTextStatus": "SCENE/PASSAGE — FULL TEXT MAY BE NEEDED",
    "status": "KEEP"
  },
  {
    "id": "NF-029",
    "world": "General Wisdom",
    "character": "Arnold Schwarzenegger",
    "source": "First Inaugural Address as Governor of California (2003)",
    "quote": "What we face may look insurmountable… What I learned is that we are always stronger than we know.",
    "highlight": "STRONGER THAN WE KNOW",
    "theme": "Self-belief; training; perseverance",
    "fullTextStatus": "FULL TEXT RECEIVED",
    "status": "KEEP"
  },
  {
    "id": "NF-031",
    "world": "General Wisdom",
    "character": "Sargent Shriver (quoted by Arnold Schwarzenegger)",
    "source": "Sargent Shriver speech tradition; quoted in Arnold Schwarzenegger, Total Recall (2012)",
    "quote": "It's not what you get out of life that counts. Break your mirrors!",
    "highlight": "BREAK YOUR MIRRORS",
    "theme": "Service; community; meaning",
    "fullTextStatus": "FULL TEXT RECEIVED",
    "status": "KEEP — attribution corrected"
  },
  {
    "id": "NF-032",
    "world": "General Wisdom",
    "character": "Arnold Schwarzenegger",
    "source": "USC commencement speech (2009)",
    "quote": "Just remember, you can't climb the ladder of success with your hands in your pockets.",
    "highlight": "HANDS OUT OF YOUR POCKETS",
    "theme": "Action; effort; initiative",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-034",
    "world": "General Wisdom",
    "character": "Wayne Gretzky",
    "source": "Attributed to Gretzky in modern proverb references",
    "quote": "You miss 100% of the shots you don't take.",
    "highlight": "TAKE THE SHOT",
    "theme": "Courage; opportunity; action",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-035",
    "world": "General Wisdom",
    "character": "Joe Sabah (quoted by Zig Ziglar)",
    "source": "Zig Ziglar, Over the Top (1994)",
    "quote": "You don't have to be great to start, but you have to start to be great.",
    "highlight": "START TO BE GREAT",
    "theme": "Starting; action; growth; courage",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-036",
    "world": "General Wisdom",
    "character": "Maya Angelou",
    "source": "Quoted by Oprah Winfrey; documented 1995",
    "quote": "You did what you knew how to do, and when you knew better, you did better.",
    "highlight": "WHEN YOU KNEW BETTER, YOU DID BETTER",
    "theme": "Growth; learning; self-compassion; accountability",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-037",
    "world": "General Wisdom",
    "character": "Suzy Kassem",
    "source": "Rise Up and Salute the Sun (2010); earlier 2008 blog",
    "quote": "Doubt kills more dreams than failure ever will.",
    "highlight": "DOUBT KILLS MORE DREAMS",
    "theme": "Self-belief; courage; doubt; dreams",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-038",
    "world": "General Wisdom",
    "character": "Samuel Beckett",
    "source": "Worstward Ho (1983)",
    "quote": "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.",
    "highlight": "FAIL BETTER",
    "theme": "Failure; persistence; experimentation; improvement",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-039",
    "world": "General Wisdom",
    "character": "Robert H. Schuller",
    "source": "Tough Times Never Last, but Tough People Do! (1983/1984 editions)",
    "quote": "Tough times never last, but tough people do.",
    "highlight": "TOUGH PEOPLE DO",
    "theme": "Resilience; adversity; endurance",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-040",
    "world": "General Wisdom",
    "character": "Albert Einstein",
    "source": "LIFE magazine, 'Old Man's Advice to Youth' (May 2, 1955)",
    "quote": "Try not to become a man of success but rather try to become a man of value.",
    "highlight": "BECOME A PERSON OF VALUE",
    "theme": "Purpose; contribution; character; values",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  },
  {
    "id": "NF-041",
    "world": "General Wisdom",
    "character": "Anonymous / origin uncertain",
    "source": "English-language saying; Chinese attribution unsupported",
    "quote": "The best time to plant a tree was 20 years ago. The second best time is now.",
    "highlight": "THE SECOND BEST TIME IS NOW",
    "theme": "Starting; regret; action; renewal",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP — attribution corrected"
  },
  {
    "id": "NF-042",
    "world": "General Wisdom",
    "character": "Laozi (Lao Tzu), traditionally ascribed",
    "source": "Tao Te Ching, chapter 64; modern English rendering",
    "quote": "A journey of a thousand miles begins with a single step.",
    "highlight": "BEGINS WITH A SINGLE STEP",
    "theme": "Starting; patience; progress; persistence",
    "fullTextStatus": "COMPLETE SHORT QUOTE / ANCHOR",
    "status": "KEEP"
  }
];
